### ISSUE TITLE
php artisan db:seed Error

### ISSUE THREAD

**Issue by daaiiaat** [haxorsprogramming/Mondry-Web#1]
Tolong bantuannya admin. Error seperti di bwah setelah melakukan perintah seperti di tittle 

Seeding: Database\Seeders\S_Raw_Material

   Illuminate\Database\QueryException

  SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'id_branch' cannot be null (SQL: insert into `tbl_raw` (`id_raw`, `raw_name`, `unit`, `deks`, `id_branch`, `stock`, `active`, `updated_at`, `created_at`) values (22a59c37-c00e-43e4-9118-5f1452e500df, Shampoo, litre, , ?, 11, 1, 2022-12-30 08:12:40, 2022-12-30 08:12:40))

  at C:\xampp\htdocs\Mondry-Web\vendor\laravel\framework\src\Illuminate\Database\Connection.php:703
    699▕         // If an exception occurs when attempting to run a query, we'll format the error
    700▕         // message to include the bindings with SQL, which will make this exception a
    701▕         // lot more helpful to the developer instead of just the database's errors.
    702▕         catch (Exception $e) {
  ➜ 703▕             throw new QueryException(
    704▕                 $query, $this->prepareBindings($bindings), $e
    705▕             );
    706▕         }
    707▕     }

    707▕     }

  1   C:\xampp\htdocs\Mondry-Web\vendor\laravel\framework\src\Illuminate\Database\Connection.php:492
      PDOException::("SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'id_branch' cannot be null")

  2   C:\xampp\htdocs\Mondry-Web\vendor\laravel\framework\src\Illuminate\Database\Connection.php:492
      PDOStatement::execute()

**Comment by haxorsprogramming** [comment]
"application under development ..." ,,

**Comment by daaiiaat** [comment]
ok admin. trimksh.
